name: build(buildpack-deps)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  buildpack-deps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [buildpack-deps]
        os: [debian]
        suite: [trixie, forky]

    steps:
      - name: Prepare configuration
        run: |
          wget -qO- https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz | sudo tar -xzf - -C /usr/local/bin/ crane
          sudo chmod +x /usr/local/bin/crane
          sudo chown root:root /usr/local/bin/crane

      - name: Checkout ${{ matrix.name }}
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }} curl image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.name }}/${{ matrix.os }}/${{ matrix.suite }}/curl
          platforms: linux/loong64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-curl-loong64
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Merge curl Images
        run: |
          crane index append -t ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-curl -m ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-curl-loong64 -m ${{ matrix.name }}:${{ matrix.suite }}

      - name: Build and push ${{ matrix.name }} scm image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.name }}/${{ matrix.os }}/${{ matrix.suite }}/scm
          platforms: linux/loong64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-scm-loong64
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Merge scm Images
        run: |
          crane index append -t ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-scm -m ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-scm-loong64 -m ${{ matrix.name }}:${{ matrix.suite }}

      - name: Build and push ${{ matrix.name }} ${{ matrix.suite }} image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.name }}/${{ matrix.os }}/${{ matrix.suite }}
          platforms: linux/loong64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-loong64
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Merge Images
        run: |
          crane index append -t ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }} -m ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.suite }}-loong64 -m ${{ matrix.name }}:${{ matrix.suite }}